# Generated by Django 5.1.4 on 2024-12-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atribut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_materi', models.CharField(max_length=255)),
                ('file_materi', models.FileField(upload_to='materi')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif')], default='aktif', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'materi',
                'db_table': 'materi',
            },
        ),
        migrations.CreateModel(
            name='perangkat_kurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perangkat_kurikulum', models.CharField(max_length=255)),
                ('file_perangkat_kurikulum', models.FileField(upload_to='perangkat_kurikulum')),
            ],
            options={
                'verbose_name_plural': 'perangkat_kurikulum',
                'db_table': 'perangkat_kurikulum',
            },
        ),
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buku', models.CharField(max_length=255)),
                ('file_buku', models.FileField(upload_to='buku/')),
                ('penerbit', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif')], default='aktif', max_length=20)),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.jenjang')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.kelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.mata_pelajaran')),
                ('sekolah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atribut.sekolah')),
            ],
            options={
                'verbose_name_plural': 'buku',
                'db_table': 'buku',
            },
        ),
    ]
