# Generated by Django 5.1.4 on 2024-12-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        ('atribut', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.guru'),
        ),
        migrations.AddField(
            model_name='materi',
            name='jenjang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.jenjang'),
        ),
        migrations.AddField(
            model_name='materi',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.kelas'),
        ),
        migrations.AddField(
            model_name='materi',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.mata_pelajaran'),
        ),
        migrations.AddField(
            model_name='materi',
            name='sekolah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.sekolah'),
        ),
        migrations.AddField(
            model_name='perangkat_kurikulum',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.guru'),
        ),
        migrations.AddField(
            model_name='perangkat_kurikulum',
            name='jenjang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.jenjang'),
        ),
        migrations.AddField(
            model_name='perangkat_kurikulum',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.kelas'),
        ),
        migrations.AddField(
            model_name='perangkat_kurikulum',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.mata_pelajaran'),
        ),
        migrations.AddField(
            model_name='perangkat_kurikulum',
            name='sekolah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.sekolah'),
        ),
    ]
