# Generated by Django 5.1.4 on 2024-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_perangkat_kurikulum_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='file_buku',
            field=models.FileField(blank=True, null=True, upload_to='buku/'),
        ),
        migrations.AlterField(
            model_name='perangkat_kurikulum',
            name='file_perangkat_kurikulum',
            field=models.FileField(blank=True, null=True, upload_to='perangkat_kurikulum'),
        ),
    ]
