# Generated by Django 5.1.4 on 2024-12-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jenjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenjang', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'jenjang',
                'db_table': 'janjang',
            },
        ),
        migrations.CreateModel(
            name='mata_pelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mata_pelajaran', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'mata_pelajaran',
                'db_table': 'mata_pelajaran',
            },
        ),
        migrations.CreateModel(
            name='sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=255)),
                ('logo_sekolah', models.ImageField(blank=True, null=True, upload_to='logo_sekolah/')),
            ],
            options={
                'verbose_name_plural': 'sekolah',
                'db_table': 'sekolah',
            },
        ),
        migrations.CreateModel(
            name='kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=255)),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atribut.jenjang')),
            ],
            options={
                'verbose_name_plural': 'kelas',
                'db_table': 'kelas',
            },
        ),
    ]
