# Generated by Django 5.1.4 on 2025-01-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='crud_buku',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guru',
            name='crud_materi',
            field=models.BooleanField(default=False),
        ),
    ]
